#Application Configuration
server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8079/product-service
    username: postgres
    password: example
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka