#Application Configuration
server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8079/shopping-service
    username: postgres
    password: example
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenTohHalfOpenEnabled: true
        failureRateThreshold: 50
        minmumNumberOfCalls: 5
        permitedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
