CREATE DATABASE "product-service";

CREATE TABLE IF NOT EXISTS CATEGORIES (
  "id" SERIAL NOT NULL,
  "name" VARCHAR(45) NOT NULL,
  PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS PRODUCTS (
  "id" SERIAL NOT NULL,
  "name" VARCHAR(45) NULL,
  "description" TEXT NULL,
  "price" DECIMAL(16,2) NULL,
  "stock" DECIMAL(16,2) NOT NULL,
  "status" VARCHAR(15) NULL,
  "create_at" TIMESTAMP NULL,
  "category_id" SERIAL NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_PRODUCTS_CATEGORIES"
    FOREIGN KEY ("category_id")
    REFERENCES CATEGORIES ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);